on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC16F877A
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F877A
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/78392dc9a003f9c6b8623a9ccac755fa
          gist_title: Pr치ctica 6 - ADC Set Point PIC16F877A CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F877A/ADC Set Point.c
          file_encoding: WINDOWS-1252
    #PIC16F887
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F887
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/9a39d329d7144c03d06ef676d971496e
          gist_title: Pr치ctica 6 - ADC Set Point PIC16F887 CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F887/ADC Set Point.c
          file_encoding: WINDOWS-1252